name: Ultimate SSH Direct Overkill

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure and Start SSH Directly
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          
          # Задаем руту нормальный пароль
          echo "root:root" | sudo chpasswd
          
          # Создаем системную папку для ключей sshd
          sudo mkdir -p /var/run/sshd
          
          # Запускаем SSH-сервер вручную на порту 22222 в фоновом режиме, минуя systemd
          sudo /usr/sbin/sshd -p 22222 &

      - name: Install Bore
        run: |
          curl -sL https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-unknown-linux-musl.tar.gz | tar -xz
          chmod +x bore
          sudo mv bore /usr/local/bin/bore

      - name: Expose Port 22222 via Bore
        run: |
          echo "=== SSH DIRECT TUNNEL IS LIVE ==="
          bore local 22222 --to bore.pub &
          
          sleep 21600
